steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --dockerfile=Dockerfile.cloud
      - --destination=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}
      - --cache=true

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--vpc-connector",
        "cache-connector",
        "--set-env-vars",
        "REDISHOST=10.132.0.3,REDISPORT=6379"
      ]
