version: "3.8"
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      PORT: 8000
      ENV: LOCALPROD
    ports:
      - "8000:8000"
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
    - "6379:6379"
    depends_on:
      - web
