version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

executors:
  python:
    docker:
    - image: circleci/python:3.8-node

jobs:
  build-test-deploy:
    executor: python
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies from cache
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies using Pipenv
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          name: Cache dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: Build custom components
          command: |
            pipenv run ./build_custom_components.sh
      - heroku/deploy-via-git:
          filters:
            branches:
              only: main

workflows:
  version: 2
  build-and-test-deploy:
    jobs:
      - build-test-deploy
